image: gradle:4.0.1-jdk8-alpine
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - gradle idea classes compileTestGroovy --no-daemon #download dependencies, compile
          - gradle run --no-daemon --stacktrace &
          - sleep 15
          - gradle test --stacktrace --no-daemon
        services:
          - db
          - mq
        environment:
          PORT: 8080
          MONGO_URL: "mongodb://127.0.0.1:27017/sample"
          MQ_URL: "amqp://admin:admin@127.0.0.1/admin"
          MAX_HEAP_SIZE: "128M"
definitions:
  services:
    mq:
      image: "rabbitmq:3.6.10-management-alpine"
      environment:
        RABBITMQ_DEFAULT_USER: "admin"
        RABBITMQ_DEFAULT_PASS: "admin"
        RABBITMQ_DEFAULT_VHOST: "admin"
    db:
      image: "mongo:3.5.7"
