version: "2"
services:
  jenkins:
    #image: "agco/jenkins-docker-compose"
    image: "istresearch/jenkins:latest"
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose"
    privileged: true
    #environment:
    #  DOCKER_HOST: "tcp://127.0.0.1:2376"
